const hotelsInfo = [
	{
		ResortTitle: "Shagor Nibash",
		specification: {
			guest: 4,
			rooms: 2,
			beds: 2,
			bathrooms: 2,
		},
		features: ["Wif Air conditioning Kitchen", "Cancellation fexibility availiable"],
		ratings: 4.9,
		totalRating: 20,
		price: 34,
		cords: { lat: 21.4171963, lng: 91.977232 },
		imgUrl: "https://i.ibb.co/KXX7Wmn/travel-img-1.png",
		title: "Cox's Bazar",
		id: "item-1",
	},
	{
		ResortTitle: "Apartment in Lost Panorama",
		specification: {
			guest: 4,
			rooms: 2,
			beds: 2,
			bathrooms: 2,
		},
		features: ["Wif Air conditioning Kitchen", "Cancellation fexibility availiable"],
		ratings: 4.5,
		totalRating: 15,
		price: 52,
		cords: { lat: 21.4172171, lng: 91.9772095 },
		imgUrl: "https://i.ibb.co/w7NjLP1/travel-img-2.png",
		title: "Cox's Bazar",
		id: "item-1",
	},
	{
		ResortTitle: "AR Lounge & Pool (r&r + b&b)",
		specification: {
			guest: 4,
			rooms: 2,
			beds: 2,
			bathrooms: 2,
		},
		features: ["Wif Air conditioning Kitchen", "Cancellation fexibility availiable"],
		ratings: 4.9,
		totalRating: 25,
		price: 44,
		cords: { lat: 21.4172171, lng: 91.9772095 },
		imgUrl: "https://i.ibb.co/wYMBf0w/travel-img-3.png",
		title: "Cox's Bazar",
		id: "item-1",
	},
	{
		ResortTitle: "Hotel Valley Garden",
		specification: {
			guest: 4,
			rooms: 2,
			beds: 2,
			bathrooms: 2,
		},
		features: ["Wif Air conditioning Kitchen", "Cancellation fexibility availiable"],
		ratings: 4.9,
		totalRating: 25,
		price: 44,
		cords: { lat: 21.4172171, lng: 91.9772095 },
		imgUrl: "https://i.ibb.co/fHWwbPP/Hotel-valley-garden.jpg",
		title: "Sreemangal",
		id: "item-2",
	},
	{
		ResortTitle: "Tea Heaven Resort",
		specification: {
			guest: 2,
			rooms: 1,
			beds: 1,
			bathrooms: 1,
		},
		features: ["Wif Air conditioning Kitchen", "Cancellation fexibility availiable"],
		ratings: 4.9,
		totalRating: 20,
		price: 34,
		cords: { lat: 21.4171963, lng: 91.977232 },
		imgUrl: "https://i.ibb.co/bR7sTj9/Standard-couple.jpg",
		title: "Sreemangal",
		id: "item-2",
	},
	{
		ResortTitle: "Patrasnana Eco Resort",
		specification: {
			guest: 4,
			rooms: 2,
			beds: 2,
			bathrooms: 2,
		},
		features: ["Wif Air conditioning Kitchen", "Cancellation fexibility availiable"],
		ratings: 4.5,
		totalRating: 15,
		price: 52,
		cords: { lat: 21.4172171, lng: 91.9772095 },
		imgUrl: "https://i.ibb.co/z6KzQKG/Family-suite.jpg",
		title: "Sreemangal",
		id: "item-2",
	},
	{
		ResortTitle: "Hotel Sonar Bangla",
		specification: {
			guest: 4,
			rooms: 2,
			beds: 2,
			bathrooms: 2,
		},
		features: ["Wif Air conditioning Kitchen", "Cancellation fexibility availiable"],
		ratings: 4.5,
		totalRating: 15,
		price: 52,
		cords: { lat: 21.4172171, lng: 91.9772095 },
		imgUrl: "https://i.ibb.co/PCzCtm4/Sonar-bangla.jpg",
		title: "Sundarbans",
		id: "item-3",
	},
	{
		ResortTitle: "Tiger Residency Resort",
		specification: {
			guest: 4,
			rooms: 2,
			beds: 2,
			bathrooms: 2,
		},
		features: ["Wif Air conditioning Kitchen", "Cancellation fexibility availiable"],
		ratings: 4.9,
		totalRating: 25,
		price: 44,
		cords: { lat: 21.4172171, lng: 91.9772095 },
		imgUrl: "https://i.ibb.co/KbGNPgw/Tiger-residency.jpg",
		title: "Sundarbans",
		id: "item-3",
	},
	{
		ResortTitle: "Jhore Jole Jongole",
		specification: {
			guest: 4,
			rooms: 2,
			beds: 2,
			bathrooms: 2,
		},
		features: ["Wif Air conditioning Kitchen", "Cancellation fexibility availiable"],
		ratings: 4.9,
		totalRating: 20,
		price: 34,
		cords: { lat: 21.4171963, lng: 91.977232 },
		imgUrl: "https://i.ibb.co/BLJ8rjG/Super-deluxe.jpg",
		title: "Sundarbans",
		id: "item-3",
	},
];

export default hotelsInfo;
